import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Locale;
import java.util.Properties;

/**
 * Bridges the in-code {@link ExperimentConfig} to algorithm classes whose
 * constructors expect the path of a {@code .properties} file
 * ({@code HAUSP_UB}, {@code EHAUSM_Inc},
 * {@code EHAUSM_Remining}, {@code Pre_HUSPM_adapt}). For every
 * {@link ExperimentConfig.DatasetRun} that needs to run, a properties file is
 * written under {@code build/configs/} with a stable name of the form
 * {@code expN_<dataset>.properties} so that the directory does not grow on
 * repeated invocations.
 *
 * <p>The generated directory is excluded from version control through
 * {@code .gitignore}.
 */
public final class ConfigBridge {

    private ConfigBridge() {}

    private static final File CONFIG_OUT_DIR = new File(ExperimentConfig.BUILD_DIR, "configs");

    static {
        if (!CONFIG_OUT_DIR.exists() && !CONFIG_OUT_DIR.mkdirs()) {
            System.err.println("[ConfigBridge] Warning: cannot create " + CONFIG_OUT_DIR);
        }
    }

    /** Materialise the run with its default minimum-utility and batch ratios. */
    public static String materialize(int experimentId, ExperimentConfig.DatasetRun run) throws IOException {
        return materialize(experimentId, run, run.minUtil, run.batchRatios);
    }

    /**
     * Materialise the run with overridden parameters. Used by Experiment 2
     * (threshold sweep), Experiment 3 (Δ schedule) and Experiment 5 (discrete
     * threshold list).
     */
    public static String materialize(int experimentId,
                                     ExperimentConfig.DatasetRun run,
                                     double minUtilOverride,
                                     double[] batchRatiosOverride) throws IOException {
        return materialize(experimentId, run, minUtilOverride, batchRatiosOverride, run.mu, "");
    }

    /**
     * Materialise the run with an overridden pre-large safety margin
     * {@code mu} (Experiment 10 sweeps it). The file name carries the value
     * so that consecutive sweep points do not overwrite each other.
     */
    public static String materialize(int experimentId,
                                     ExperimentConfig.DatasetRun run,
                                     double minUtilOverride,
                                     double[] batchRatiosOverride,
                                     double muOverride) throws IOException {
        return materialize(experimentId, run, minUtilOverride, batchRatiosOverride, muOverride,
                String.format(Locale.US, "_mu%.3f", muOverride));
    }

    private static String materialize(int experimentId,
                                      ExperimentConfig.DatasetRun run,
                                      double minUtilOverride,
                                      double[] batchRatiosOverride,
                                      double muOverride,
                                      String nameSuffix) throws IOException {
        if (!CONFIG_OUT_DIR.exists()) CONFIG_OUT_DIR.mkdirs();

        ExperimentConfig.DatasetSpec ds = run.dataset;

        Properties p = new Properties();
        p.setProperty("dataset.path",       ds.seqPath);
        p.setProperty("eui.path",           ds.euiPath);
        p.setProperty("minUtil.percentage", String.format(Locale.US, "%.10f", minUtilOverride));
        p.setProperty("mu.ratio",           String.format(Locale.US, "%.6f", muOverride));
        p.setProperty("batch.ratios",       joinDoubles(batchRatiosOverride));
        p.setProperty("output.dir",         ExperimentConfig.RESULTS_DIR + "/" + ds.name);

        String fname = String.format("exp%d_%s%s.properties", experimentId, ds.name, nameSuffix);
        File out = new File(CONFIG_OUT_DIR, fname);
        try (FileOutputStream fos = new FileOutputStream(out)) {
            p.store(fos, "Auto-generated by ConfigBridge; edit ExperimentConfig.java instead.");
        }
        return out.getAbsolutePath();
    }

    private static String joinDoubles(double[] arr) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < arr.length; i++) {
            if (i > 0) sb.append(',');
            sb.append(String.format(Locale.US, "%.6f", arr[i]));
        }
        return sb.toString();
    }
}
