#!/usr/bin/env bash
# Generated by analysis/stale_cells.py -- do not edit by hand; regenerate instead.
# Datasets: BIBLE, BMS1_SPMF, C8T1S5I8N5K, FIFA, KOSARAK, LEVIATHAN, SIGN, TAFENG. One JVM per arm; run.sh supplies heap, cap and caffeinate.
# Groups run cheapest first; each group measures every arm of one comparison back to back.
# Stops at the first failing command, so a partial campaign is visible rather than silent;
# every command carries --resume, so running this file again continues where it stopped.
# Times in [est ...] are extrapolated from earlier runs of the same cells, not measured.
# DRY_RUN=1 prints the commands instead of running them.
# To stop cleanly: touch /tmp/hausp-stop -- the command running now finishes, then the file
# exits. Ctrl-C instead abandons a trial half-written, and its re-run appends a second copy
# of the batches already written (the audit reports it; see duplicated_keys).
set -euo pipefail
cd "$(dirname "$0")/.."
run() { if [ -n "${DRY_RUN:-}" ]; then printf "%q " "$@"; echo; else "$@"; fi; }
stop_check() { if [ -e /tmp/hausp-stop ]; then rm -f /tmp/hausp-stop; echo "[batch] $(date) stop requested; run this file again to continue"; exit 0; fi; }
rm -f /tmp/hausp-stop
echo "[batch] $(date) start at $(git rev-parse --short HEAD)"
stop_check
echo "[batch] $(date +%H:%M) 1/258 [est 0 min, cumulative 0.0 h] count exp6 C8T1S5I8N5K EHAUSM-R,HAUSP-UB[noEUCS]"
if [ "$(grep -c "^C8T1S5I8N5K," results-2026-09l/exp6/experiment6_multibatch_accuracy.csv 2>/dev/null || true)" -ge 5 ]; then echo '[batch] exp6 C8T1S5I8N5K already complete in results-2026-09l/exp6/experiment6_multibatch_accuracy.csv'; else run ./scripts/run.sh 6 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-R,HAUSP-UB[noEUCS]" --repeats 1 --results-dir results-2026-09l --resume; fi
stop_check
echo "[batch] $(date +%H:%M) 2/258 [est 0 min, cumulative 0.0 h] mem exp3 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 3/258 [est 0 min, cumulative 0.0 h] mem exp3 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 4/258 [est 0 min, cumulative 0.0 h] mem exp9 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 5/258 [est 0 min, cumulative 0.0 h] mem exp9 C8T1S5I8N5K EHAUSM-R"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-R" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 6/258 [est 0 min, cumulative 0.0 h] mem exp9 C8T1S5I8N5K HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 7/258 [est 0 min, cumulative 0.0 h] mem exp9 C8T1S5I8N5K HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 8/258 [est 0 min, cumulative 0.0 h] mem exp9 C8T1S5I8N5K HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL2+noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 9/258 [est 0 min, cumulative 0.0 h] mem exp9 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 10/258 [est 1 min, cumulative 0.0 h] mem exp3 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset sign --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 11/258 [est 0 min, cumulative 0.0 h] time exp9 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 12/258 [est 0 min, cumulative 0.0 h] time exp9 C8T1S5I8N5K EHAUSM-R"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 13/258 [est 0 min, cumulative 0.0 h] time exp9 C8T1S5I8N5K HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 14/258 [est 0 min, cumulative 0.0 h] time exp9 C8T1S5I8N5K HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 15/258 [est 0 min, cumulative 0.0 h] time exp9 C8T1S5I8N5K HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 16/258 [est 0 min, cumulative 0.0 h] time exp9 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 17/258 [est 0 min, cumulative 0.0 h] mem exp3 TAFENG EHAUSM-R"
run ./scripts/run.sh 3 --dataset tafeng --algo "EHAUSM-R" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 18/258 [est 0 min, cumulative 0.0 h] mem exp3 TAFENG EHAUSM-I"
run ./scripts/run.sh 3 --dataset tafeng --algo "EHAUSM-I" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 19/258 [est 0 min, cumulative 0.1 h] mem exp3 TAFENG Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset tafeng --algo "Pre-HAUSPM" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 20/258 [est 0 min, cumulative 0.1 h] mem exp3 TAFENG HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset tafeng --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 21/258 [est 0 min, cumulative 0.1 h] time exp4 C8T1S5I8N5K EHAUSM-R"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 22/258 [est 0 min, cumulative 0.1 h] time exp4 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 23/258 [est 1 min, cumulative 0.1 h] time exp4 C8T1S5I8N5K Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "Pre-HAUSPM" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 24/258 [est 0 min, cumulative 0.1 h] time exp4 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 25/258 [est 1 min, cumulative 0.1 h] mem exp3 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 26/258 [est 1 min, cumulative 0.1 h] time exp8 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 8 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 27/258 [est 1 min, cumulative 0.1 h] time exp8 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 8 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 28/258 [est 1 min, cumulative 0.1 h] time exp9 LEVIATHAN EHAUSM-I"
run ./scripts/run.sh 9 --dataset leviathan --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 29/258 [est 1 min, cumulative 0.2 h] time exp9 LEVIATHAN EHAUSM-R"
run ./scripts/run.sh 9 --dataset leviathan --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 30/258 [est 0 min, cumulative 0.2 h] time exp9 LEVIATHAN HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset leviathan --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 31/258 [est 0 min, cumulative 0.2 h] time exp9 LEVIATHAN HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset leviathan --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 32/258 [est 0 min, cumulative 0.2 h] time exp9 LEVIATHAN HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset leviathan --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 33/258 [est 0 min, cumulative 0.2 h] time exp9 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 34/258 [est 1 min, cumulative 0.2 h] time exp4 LEVIATHAN EHAUSM-R"
run ./scripts/run.sh 4 --dataset leviathan --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 35/258 [est 1 min, cumulative 0.2 h] time exp4 LEVIATHAN EHAUSM-I"
run ./scripts/run.sh 4 --dataset leviathan --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 36/258 [est 1 min, cumulative 0.2 h] time exp4 LEVIATHAN Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset leviathan --algo "Pre-HAUSPM" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 37/258 [est 0 min, cumulative 0.2 h] time exp4 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 38/258 [est 3 min, cumulative 0.3 h] time exp8 LEVIATHAN EHAUSM-I"
run ./scripts/run.sh 8 --dataset leviathan --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 39/258 [est 1 min, cumulative 0.3 h] time exp8 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 8 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 40/258 [est 1 min, cumulative 0.3 h] mem exp9 TAFENG EHAUSM-I"
run ./scripts/run.sh 9 --dataset tafeng --algo "EHAUSM-I" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 41/258 [est 1 min, cumulative 0.3 h] mem exp9 TAFENG EHAUSM-R"
run ./scripts/run.sh 9 --dataset tafeng --algo "EHAUSM-R" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 42/258 [est 1 min, cumulative 0.3 h] mem exp9 TAFENG HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 43/258 [est 1 min, cumulative 0.3 h] mem exp9 TAFENG HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 44/258 [est 0 min, cumulative 0.3 h] mem exp9 TAFENG HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noL2+noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 45/258 [est 0 min, cumulative 0.3 h] mem exp9 TAFENG HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noEUCS]" --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 46/258 [est 1 min, cumulative 0.4 h] time exp3 C8T1S5I8N5K EHAUSM-R"
run ./scripts/run.sh 3 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 47/258 [est 1 min, cumulative 0.4 h] time exp3 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 3 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 48/258 [est 2 min, cumulative 0.4 h] time exp3 C8T1S5I8N5K Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset syn_c8t1s5i8n5k --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 49/258 [est 1 min, cumulative 0.4 h] time exp3 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 50/258 [est 1 min, cumulative 0.4 h] mem exp11 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 11 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --k 100 --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 51/258 [est 0 min, cumulative 0.4 h] mem exp11 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 11 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --k 100 --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 52/258 [est 4 min, cumulative 0.5 h] mem exp11 C8T1S5I8N5K Pre-HAUSPM"
run ./scripts/run.sh 11 --dataset syn_c8t1s5i8n5k --algo "Pre-HAUSPM" --k 100 --repeats 1 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 53/258 [est 6 min, cumulative 0.6 h] mem exp3 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset fifa --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 54/258 [est 2 min, cumulative 0.6 h] time exp9 TAFENG EHAUSM-I"
run ./scripts/run.sh 9 --dataset tafeng --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 55/258 [est 2 min, cumulative 0.7 h] time exp9 TAFENG EHAUSM-R"
run ./scripts/run.sh 9 --dataset tafeng --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 56/258 [est 1 min, cumulative 0.7 h] time exp9 TAFENG HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 57/258 [est 1 min, cumulative 0.7 h] time exp9 TAFENG HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 58/258 [est 1 min, cumulative 0.7 h] time exp9 TAFENG HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 59/258 [est 1 min, cumulative 0.7 h] time exp9 TAFENG HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset tafeng --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 60/258 [est 7 min, cumulative 0.9 h] time exp8 SIGN EHAUSM-I"
run ./scripts/run.sh 8 --dataset sign --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 61/258 [est 2 min, cumulative 0.9 h] time exp8 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 8 --dataset sign --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 62/258 [est 3 min, cumulative 0.9 h] time exp9 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 9 --dataset bms1_spmf --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 63/258 [est 3 min, cumulative 1.0 h] time exp9 BMS1_SPMF EHAUSM-R"
run ./scripts/run.sh 9 --dataset bms1_spmf --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 64/258 [est 2 min, cumulative 1.0 h] time exp9 BMS1_SPMF HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset bms1_spmf --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 65/258 [est 2 min, cumulative 1.0 h] time exp9 BMS1_SPMF HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset bms1_spmf --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 66/258 [est 1 min, cumulative 1.1 h] time exp9 BMS1_SPMF HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset bms1_spmf --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 67/258 [est 1 min, cumulative 1.1 h] time exp9 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 68/258 [est 4 min, cumulative 1.2 h] time exp9 BIBLE EHAUSM-I"
run ./scripts/run.sh 9 --dataset bible --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 69/258 [est 4 min, cumulative 1.2 h] time exp9 BIBLE EHAUSM-R"
run ./scripts/run.sh 9 --dataset bible --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 70/258 [est 1 min, cumulative 1.2 h] time exp9 BIBLE HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset bible --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 71/258 [est 1 min, cumulative 1.3 h] time exp9 BIBLE HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset bible --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 72/258 [est 1 min, cumulative 1.3 h] time exp9 BIBLE HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset bible --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 73/258 [est 1 min, cumulative 1.3 h] time exp9 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset bible --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 74/258 [est 3 min, cumulative 1.4 h] time exp3 LEVIATHAN EHAUSM-R"
run ./scripts/run.sh 3 --dataset leviathan --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 75/258 [est 4 min, cumulative 1.4 h] time exp3 LEVIATHAN EHAUSM-I"
run ./scripts/run.sh 3 --dataset leviathan --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 76/258 [est 5 min, cumulative 1.5 h] time exp3 LEVIATHAN Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset leviathan --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 77/258 [est 1 min, cumulative 1.5 h] time exp3 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 78/258 [est 6 min, cumulative 1.6 h] time exp9 SIGN EHAUSM-I"
run ./scripts/run.sh 9 --dataset sign --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 79/258 [est 5 min, cumulative 1.7 h] time exp9 SIGN EHAUSM-R"
run ./scripts/run.sh 9 --dataset sign --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 80/258 [est 2 min, cumulative 1.7 h] time exp9 SIGN HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset sign --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 81/258 [est 2 min, cumulative 1.8 h] time exp9 SIGN HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset sign --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 82/258 [est 1 min, cumulative 1.8 h] time exp9 SIGN HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset sign --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 83/258 [est 1 min, cumulative 1.8 h] time exp9 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset sign --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 84/258 [est 5 min, cumulative 1.9 h] time exp4 SIGN EHAUSM-R"
run ./scripts/run.sh 4 --dataset sign --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 85/258 [est 5 min, cumulative 2.0 h] time exp4 SIGN EHAUSM-I"
run ./scripts/run.sh 4 --dataset sign --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 86/258 [est 7 min, cumulative 2.1 h] time exp4 SIGN Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset sign --algo "Pre-HAUSPM" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 87/258 [est 0 min, cumulative 2.1 h] time exp4 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset sign --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 88/258 [est 5 min, cumulative 2.2 h] time exp3 SIGN EHAUSM-R"
run ./scripts/run.sh 3 --dataset sign --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 89/258 [est 5 min, cumulative 2.3 h] time exp3 SIGN EHAUSM-I"
run ./scripts/run.sh 3 --dataset sign --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 90/258 [est 7 min, cumulative 2.4 h] time exp3 SIGN Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset sign --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 91/258 [est 5 min, cumulative 2.4 h] time exp3 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset sign --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 92/258 [est 19 min, cumulative 2.8 h] time exp8 BIBLE EHAUSM-I"
run ./scripts/run.sh 8 --dataset bible --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 93/258 [est 5 min, cumulative 2.8 h] time exp8 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 8 --dataset bible --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 94/258 [est 9 min, cumulative 3.0 h] time exp3 BIBLE EHAUSM-R"
run ./scripts/run.sh 3 --dataset bible --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 95/258 [est 8 min, cumulative 3.1 h] time exp3 BIBLE EHAUSM-I"
run ./scripts/run.sh 3 --dataset bible --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 96/258 [est 11 min, cumulative 3.3 h] time exp3 BIBLE Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset bible --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 97/258 [est 3 min, cumulative 3.3 h] time exp3 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset bible --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 98/258 [est 9 min, cumulative 3.5 h] time exp4 BIBLE EHAUSM-R"
run ./scripts/run.sh 4 --dataset bible --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 99/258 [est 9 min, cumulative 3.6 h] time exp4 BIBLE EHAUSM-I"
run ./scripts/run.sh 4 --dataset bible --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 100/258 [est 12 min, cumulative 3.9 h] time exp4 BIBLE Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset bible --algo "Pre-HAUSPM" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 101/258 [est 0 min, cumulative 3.9 h] time exp4 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset bible --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 102/258 [est 9 min, cumulative 4.0 h] mem exp3 BIBLE EHAUSM-R"
run ./scripts/run.sh 3 --dataset bible --algo "EHAUSM-R" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 103/258 [est 8 min, cumulative 4.1 h] mem exp3 BIBLE EHAUSM-I"
run ./scripts/run.sh 3 --dataset bible --algo "EHAUSM-I" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 104/258 [est 11 min, cumulative 4.3 h] mem exp3 BIBLE Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset bible --algo "Pre-HAUSPM" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 105/258 [est 3 min, cumulative 4.4 h] mem exp3 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset bible --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 106/258 [est 8 min, cumulative 4.5 h] time exp7 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 7 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 107/258 [est 10 min, cumulative 4.7 h] time exp7 LEVIATHAN EHAUSM-I"
run ./scripts/run.sh 7 --dataset leviathan --algo "EHAUSM-I" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 108/258 [est 14 min, cumulative 4.9 h] time exp7 LEVIATHAN Pre-HAUSPM"
run ./scripts/run.sh 7 --dataset leviathan --algo "Pre-HAUSPM" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 109/258 [est 7 min, cumulative 5.0 h] time exp4 KOSARAK EHAUSM-R"
run ./scripts/run.sh 4 --dataset kosarak --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 110/258 [est 8 min, cumulative 5.2 h] time exp4 KOSARAK EHAUSM-I"
run ./scripts/run.sh 4 --dataset kosarak --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 111/258 [est 16 min, cumulative 5.4 h] time exp4 KOSARAK Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset kosarak --algo "Pre-HAUSPM" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 112/258 [est 0 min, cumulative 5.4 h] time exp4 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 113/258 [est 28 min, cumulative 5.9 h] time exp8 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 8 --dataset bms1_spmf --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 114/258 [est 12 min, cumulative 6.1 h] time exp8 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 8 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 115/258 [est 3 min, cumulative 6.1 h] time exp4 BMS1_SPMF EHAUSM-R"
run ./scripts/run.sh 4 --dataset bms1_spmf --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 116/258 [est 4 min, cumulative 6.2 h] time exp4 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 4 --dataset bms1_spmf --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 117/258 [est 37 min, cumulative 6.8 h] time exp4 BMS1_SPMF Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset bms1_spmf --algo "Pre-HAUSPM" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 118/258 [est 0 min, cumulative 6.8 h] time exp4 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 119/258 [est 10 min, cumulative 7.0 h] time exp3 KOSARAK EHAUSM-R"
run ./scripts/run.sh 3 --dataset kosarak --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 120/258 [est 11 min, cumulative 7.2 h] time exp3 KOSARAK EHAUSM-I"
run ./scripts/run.sh 3 --dataset kosarak --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 121/258 [est 21 min, cumulative 7.5 h] time exp3 KOSARAK Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset kosarak --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 122/258 [est 5 min, cumulative 7.6 h] time exp3 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 123/258 [est 52 min, cumulative 8.5 h] time exp8 KOSARAK EHAUSM-I"
run ./scripts/run.sh 8 --dataset kosarak --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 124/258 [est 20 min, cumulative 8.8 h] time exp8 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 8 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 125/258 [est 90 min, cumulative 10.3 h] mem exp4 BIBLE HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset bible --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 126/258 [est 90 min, cumulative 11.8 h] mem exp4 BMS1_SPMF HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset bms1_spmf --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 127/258 [est 90 min, cumulative 13.3 h] mem exp4 FIFA HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset fifa --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 128/258 [est 90 min, cumulative 14.8 h] mem exp4 KOSARAK HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset kosarak --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 129/258 [est 90 min, cumulative 16.3 h] mem exp4 LEVIATHAN HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset leviathan --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 130/258 [est 90 min, cumulative 17.8 h] mem exp4 SIGN HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset sign --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 131/258 [est 0 min, cumulative 17.8 h] mem exp4 C8T1S5I8N5K EHAUSM-R"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-R" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 132/258 [est 0 min, cumulative 17.8 h] mem exp4 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 133/258 [est 1 min, cumulative 17.8 h] mem exp4 C8T1S5I8N5K Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "Pre-HAUSPM" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 134/258 [est 90 min, cumulative 19.3 h] mem exp4 C8T1S5I8N5K HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 135/258 [est 0 min, cumulative 19.3 h] mem exp4 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 136/258 [est 7 min, cumulative 19.4 h] mem exp3 BMS1_SPMF EHAUSM-R"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "EHAUSM-R" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 137/258 [est 8 min, cumulative 19.6 h] mem exp3 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "EHAUSM-I" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 138/258 [est 75 min, cumulative 20.8 h] mem exp3 BMS1_SPMF Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "Pre-HAUSPM" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 139/258 [est 2 min, cumulative 20.9 h] mem exp3 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 140/258 [est 1 min, cumulative 20.9 h] time exp2 LEVIATHAN EHAUSM-I"
run ./scripts/run.sh 2 --dataset leviathan --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 141/258 [est 90 min, cumulative 22.4 h] time exp2 LEVIATHAN HAUSP-UB-L1"
run ./scripts/run.sh 2 --dataset leviathan --algo "HAUSP-UB-L1" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 142/258 [est 0 min, cumulative 22.4 h] time exp2 LEVIATHAN HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 2 --dataset leviathan --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 143/258 [est 0 min, cumulative 22.4 h] time exp2 LEVIATHAN HAUSP-UB[noL3+noEUCS]"
run ./scripts/run.sh 2 --dataset leviathan --algo "HAUSP-UB[noL3+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 144/258 [est 0 min, cumulative 22.4 h] time exp2 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 2 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 145/258 [est 5 min, cumulative 22.5 h] time exp2 SIGN EHAUSM-I"
run ./scripts/run.sh 2 --dataset sign --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 146/258 [est 90 min, cumulative 24.0 h] time exp2 SIGN HAUSP-UB-L1"
run ./scripts/run.sh 2 --dataset sign --algo "HAUSP-UB-L1" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 147/258 [est 1 min, cumulative 24.0 h] time exp2 SIGN HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 2 --dataset sign --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 148/258 [est 1 min, cumulative 24.0 h] time exp2 SIGN HAUSP-UB[noL3+noEUCS]"
run ./scripts/run.sh 2 --dataset sign --algo "HAUSP-UB[noL3+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 149/258 [est 1 min, cumulative 24.0 h] time exp2 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 2 --dataset sign --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 150/258 [est 4 min, cumulative 24.1 h] time exp2 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 2 --dataset bms1_spmf --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 151/258 [est 90 min, cumulative 25.6 h] time exp2 BMS1_SPMF HAUSP-UB-L1"
run ./scripts/run.sh 2 --dataset bms1_spmf --algo "HAUSP-UB-L1" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 152/258 [est 2 min, cumulative 25.6 h] time exp2 BMS1_SPMF HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 2 --dataset bms1_spmf --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 153/258 [est 2 min, cumulative 25.6 h] time exp2 BMS1_SPMF HAUSP-UB[noL3+noEUCS]"
run ./scripts/run.sh 2 --dataset bms1_spmf --algo "HAUSP-UB[noL3+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 154/258 [est 1 min, cumulative 25.7 h] time exp2 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 2 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 155/258 [est 75 min, cumulative 26.9 h] time exp8 FIFA EHAUSM-I"
run ./scripts/run.sh 8 --dataset fifa --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 156/258 [est 25 min, cumulative 27.3 h] time exp8 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 8 --dataset fifa --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 157/258 [est 4 min, cumulative 27.4 h] time exp1 BIBLE EHAUSM-R"
run ./scripts/run.sh 1 --dataset bible --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 158/258 [est 4 min, cumulative 27.5 h] time exp1 BIBLE EHAUSM-I"
run ./scripts/run.sh 1 --dataset bible --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 159/258 [est 5 min, cumulative 27.5 h] time exp1 BIBLE Pre-HAUSPM"
run ./scripts/run.sh 1 --dataset bible --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 160/258 [est 90 min, cumulative 29.0 h] time exp1 BIBLE HAUSP-UB-L1"
run ./scripts/run.sh 1 --dataset bible --algo "HAUSP-UB-L1" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 161/258 [est 1 min, cumulative 29.1 h] time exp1 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 1 --dataset bible --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 162/258 [est 5 min, cumulative 29.1 h] time exp1 SIGN EHAUSM-R"
run ./scripts/run.sh 1 --dataset sign --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 163/258 [est 6 min, cumulative 29.2 h] time exp1 SIGN EHAUSM-I"
run ./scripts/run.sh 1 --dataset sign --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 164/258 [est 7 min, cumulative 29.4 h] time exp1 SIGN Pre-HAUSPM"
run ./scripts/run.sh 1 --dataset sign --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 165/258 [est 90 min, cumulative 30.9 h] time exp1 SIGN HAUSP-UB-L1"
run ./scripts/run.sh 1 --dataset sign --algo "HAUSP-UB-L1" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 166/258 [est 1 min, cumulative 30.9 h] time exp1 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 1 --dataset sign --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 167/258 [est 10 min, cumulative 31.0 h] time exp2 BIBLE EHAUSM-I"
run ./scripts/run.sh 2 --dataset bible --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 168/258 [est 90 min, cumulative 32.5 h] time exp2 BIBLE HAUSP-UB-L1"
run ./scripts/run.sh 2 --dataset bible --algo "HAUSP-UB-L1" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 169/258 [est 3 min, cumulative 32.6 h] time exp2 BIBLE HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 2 --dataset bible --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 170/258 [est 3 min, cumulative 32.6 h] time exp2 BIBLE HAUSP-UB[noL3+noEUCS]"
run ./scripts/run.sh 2 --dataset bible --algo "HAUSP-UB[noL3+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 171/258 [est 3 min, cumulative 32.7 h] time exp2 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 2 --dataset bible --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 172/258 [est 38 min, cumulative 33.3 h] time exp9 FIFA EHAUSM-I"
run ./scripts/run.sh 9 --dataset fifa --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 173/258 [est 34 min, cumulative 33.9 h] time exp9 FIFA EHAUSM-R"
run ./scripts/run.sh 9 --dataset fifa --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 174/258 [est 15 min, cumulative 34.1 h] time exp9 FIFA HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset fifa --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 175/258 [est 15 min, cumulative 34.4 h] time exp9 FIFA HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset fifa --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 176/258 [est 14 min, cumulative 34.6 h] time exp9 FIFA HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset fifa --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 177/258 [est 14 min, cumulative 34.9 h] time exp9 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset fifa --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 178/258 [est 3 min, cumulative 34.9 h] time exp1 BMS1_SPMF EHAUSM-R"
run ./scripts/run.sh 1 --dataset bms1_spmf --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 179/258 [est 4 min, cumulative 35.0 h] time exp1 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 1 --dataset bms1_spmf --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 180/258 [est 34 min, cumulative 35.5 h] time exp1 BMS1_SPMF Pre-HAUSPM"
run ./scripts/run.sh 1 --dataset bms1_spmf --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 181/258 [est 90 min, cumulative 37.0 h] time exp1 BMS1_SPMF HAUSP-UB-L1"
run ./scripts/run.sh 1 --dataset bms1_spmf --algo "HAUSP-UB-L1" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 182/258 [est 1 min, cumulative 37.1 h] time exp1 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 1 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 183/258 [est 36 min, cumulative 37.7 h] time exp9 KOSARAK EHAUSM-I"
run ./scripts/run.sh 9 --dataset kosarak --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 184/258 [est 32 min, cumulative 38.2 h] time exp9 KOSARAK EHAUSM-R"
run ./scripts/run.sh 9 --dataset kosarak --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 185/258 [est 17 min, cumulative 38.5 h] time exp9 KOSARAK HAUSP-UB[noL2+L3@node+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset kosarak --algo "HAUSP-UB[noL2+L3@node+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 186/258 [est 16 min, cumulative 38.8 h] time exp9 KOSARAK HAUSP-UB[noL2+nopool+noEUCS]"
run ./scripts/run.sh 9 --dataset kosarak --algo "HAUSP-UB[noL2+nopool+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 187/258 [est 16 min, cumulative 39.0 h] time exp9 KOSARAK HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 9 --dataset kosarak --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 188/258 [est 16 min, cumulative 39.3 h] time exp9 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 9 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 189/258 [est 34 min, cumulative 39.9 h] time exp4 FIFA EHAUSM-R"
run ./scripts/run.sh 4 --dataset fifa --algo "EHAUSM-R" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 190/258 [est 39 min, cumulative 40.5 h] time exp4 FIFA EHAUSM-I"
run ./scripts/run.sh 4 --dataset fifa --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 191/258 [est 68 min, cumulative 41.6 h] time exp4 FIFA Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset fifa --algo "Pre-HAUSPM" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 192/258 [est 0 min, cumulative 41.6 h] time exp4 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset fifa --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 193/258 [est 27 min, cumulative 42.1 h] time exp2 KOSARAK EHAUSM-I"
run ./scripts/run.sh 2 --dataset kosarak --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 194/258 [est 90 min, cumulative 43.6 h] time exp2 KOSARAK HAUSP-UB-L1"
run ./scripts/run.sh 2 --dataset kosarak --algo "HAUSP-UB-L1" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 195/258 [est 11 min, cumulative 43.8 h] time exp2 KOSARAK HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 2 --dataset kosarak --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 196/258 [est 11 min, cumulative 43.9 h] time exp2 KOSARAK HAUSP-UB[noL3+noEUCS]"
run ./scripts/run.sh 2 --dataset kosarak --algo "HAUSP-UB[noL3+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 197/258 [est 10 min, cumulative 44.1 h] time exp2 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 2 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 198/258 [est 9 min, cumulative 44.3 h] time exp3 BMS1_SPMF EHAUSM-R"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 199/258 [est 11 min, cumulative 44.4 h] time exp3 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 200/258 [est 124 min, cumulative 46.5 h] time exp3 BMS1_SPMF Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 201/258 [est 5 min, cumulative 46.6 h] time exp3 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 202/258 [est 2 min, cumulative 46.6 h] mem exp4 TAFENG EHAUSM-R"
run ./scripts/run.sh 4 --dataset tafeng --algo "EHAUSM-R" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 203/258 [est 3 min, cumulative 46.7 h] mem exp4 TAFENG EHAUSM-I"
run ./scripts/run.sh 4 --dataset tafeng --algo "EHAUSM-I" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 204/258 [est 57 min, cumulative 47.6 h] mem exp4 TAFENG Pre-HAUSPM"
run ./scripts/run.sh 4 --dataset tafeng --algo "Pre-HAUSPM" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 205/258 [est 90 min, cumulative 49.1 h] mem exp4 TAFENG HAUSP-UB-L1"
run ./scripts/run.sh 4 --dataset tafeng --algo "HAUSP-UB-L1" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 206/258 [est 1 min, cumulative 49.1 h] mem exp4 TAFENG HAUSP-UB[noEUCS]"
run ./scripts/run.sh 4 --dataset tafeng --algo "HAUSP-UB[noEUCS]" --repeats 3 --mem-mode live --results-dir results-2026-09l/mem --resume
stop_check
echo "[batch] $(date +%H:%M) 207/258 [est 1 min, cumulative 49.1 h] time exp1 C8T1S5I8N5K EHAUSM-R"
run ./scripts/run.sh 1 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 208/258 [est 1 min, cumulative 49.1 h] time exp1 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 1 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 209/258 [est 1 min, cumulative 49.2 h] time exp1 C8T1S5I8N5K Pre-HAUSPM"
run ./scripts/run.sh 1 --dataset syn_c8t1s5i8n5k --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 210/258 [est 180 min, cumulative 52.2 h] time exp1 C8T1S5I8N5K HAUSP-UB-L1"
run ./scripts/run.sh 1 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB-L1" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 211/258 [est 0 min, cumulative 52.2 h] time exp1 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 1 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 212/258 [est 1 min, cumulative 52.2 h] time exp1 LEVIATHAN EHAUSM-R"
run ./scripts/run.sh 1 --dataset leviathan --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 213/258 [est 1 min, cumulative 52.2 h] time exp1 LEVIATHAN EHAUSM-I"
run ./scripts/run.sh 1 --dataset leviathan --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 214/258 [est 1 min, cumulative 52.2 h] time exp1 LEVIATHAN Pre-HAUSPM"
run ./scripts/run.sh 1 --dataset leviathan --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 215/258 [est 180 min, cumulative 55.2 h] time exp1 LEVIATHAN HAUSP-UB-L1"
run ./scripts/run.sh 1 --dataset leviathan --algo "HAUSP-UB-L1" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 216/258 [est 1 min, cumulative 55.2 h] time exp1 LEVIATHAN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 1 --dataset leviathan --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 217/258 [est 182 min, cumulative 58.3 h] time exp7 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 7 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 218/258 [est 1 min, cumulative 58.3 h] time exp7 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 7 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 219/258 [est 1 min, cumulative 58.3 h] time exp7 C8T1S5I8N5K Pre-HAUSPM"
run ./scripts/run.sh 7 --dataset syn_c8t1s5i8n5k --algo "Pre-HAUSPM" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 220/258 [est 44 min, cumulative 59.0 h] time exp3 FIFA EHAUSM-R"
run ./scripts/run.sh 3 --dataset fifa --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 221/258 [est 47 min, cumulative 59.8 h] time exp3 FIFA EHAUSM-I"
run ./scripts/run.sh 3 --dataset fifa --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 222/258 [est 79 min, cumulative 61.1 h] time exp3 FIFA Pre-HAUSPM"
run ./scripts/run.sh 3 --dataset fifa --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 223/258 [est 18 min, cumulative 61.4 h] time exp3 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 3 --dataset fifa --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 224/258 [est 1 min, cumulative 61.4 h] time exp2 C8T1S5I8N5K EHAUSM-I"
run ./scripts/run.sh 2 --dataset syn_c8t1s5i8n5k --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 225/258 [est 222 min, cumulative 65.2 h] time exp2 C8T1S5I8N5K HAUSP-UB-L1"
run ./scripts/run.sh 2 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB-L1" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 226/258 [est 0 min, cumulative 65.2 h] time exp2 C8T1S5I8N5K HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 2 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 227/258 [est 0 min, cumulative 65.2 h] time exp2 C8T1S5I8N5K HAUSP-UB[noL3+noEUCS]"
run ./scripts/run.sh 2 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noL3+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 228/258 [est 0 min, cumulative 65.2 h] time exp2 C8T1S5I8N5K HAUSP-UB[noEUCS]"
run ./scripts/run.sh 2 --dataset syn_c8t1s5i8n5k --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 229/258 [est 35 min, cumulative 65.7 h] time exp1 FIFA EHAUSM-R"
run ./scripts/run.sh 1 --dataset fifa --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 230/258 [est 39 min, cumulative 66.4 h] time exp1 FIFA EHAUSM-I"
run ./scripts/run.sh 1 --dataset fifa --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 231/258 [est 63 min, cumulative 67.4 h] time exp1 FIFA Pre-HAUSPM"
run ./scripts/run.sh 1 --dataset fifa --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 232/258 [est 90 min, cumulative 68.9 h] time exp1 FIFA HAUSP-UB-L1"
run ./scripts/run.sh 1 --dataset fifa --algo "HAUSP-UB-L1" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 233/258 [est 14 min, cumulative 69.2 h] time exp1 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 1 --dataset fifa --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 234/258 [est 33 min, cumulative 69.7 h] time exp1 KOSARAK EHAUSM-R"
run ./scripts/run.sh 1 --dataset kosarak --algo "EHAUSM-R" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 235/258 [est 37 min, cumulative 70.3 h] time exp1 KOSARAK EHAUSM-I"
run ./scripts/run.sh 1 --dataset kosarak --algo "EHAUSM-I" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 236/258 [est 99 min, cumulative 72.0 h] time exp1 KOSARAK Pre-HAUSPM"
run ./scripts/run.sh 1 --dataset kosarak --algo "Pre-HAUSPM" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 237/258 [est 90 min, cumulative 73.5 h] time exp1 KOSARAK HAUSP-UB-L1"
run ./scripts/run.sh 1 --dataset kosarak --algo "HAUSP-UB-L1" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 238/258 [est 16 min, cumulative 73.8 h] time exp1 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 1 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 239/258 [est 109 min, cumulative 75.6 h] time exp2 FIFA EHAUSM-I"
run ./scripts/run.sh 2 --dataset fifa --algo "EHAUSM-I" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 240/258 [est 90 min, cumulative 77.1 h] time exp2 FIFA HAUSP-UB-L1"
run ./scripts/run.sh 2 --dataset fifa --algo "HAUSP-UB-L1" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 241/258 [est 36 min, cumulative 77.7 h] time exp2 FIFA HAUSP-UB[noL2+noEUCS]"
run ./scripts/run.sh 2 --dataset fifa --algo "HAUSP-UB[noL2+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 242/258 [est 35 min, cumulative 78.3 h] time exp2 FIFA HAUSP-UB[noL3+noEUCS]"
run ./scripts/run.sh 2 --dataset fifa --algo "HAUSP-UB[noL3+noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 243/258 [est 32 min, cumulative 78.8 h] time exp2 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 2 --dataset fifa --algo "HAUSP-UB[noEUCS]" --repeats 3 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 244/258 [est 38 min, cumulative 79.4 h] time exp7 BIBLE HAUSP-UB[noEUCS]"
run ./scripts/run.sh 7 --dataset bible --algo "HAUSP-UB[noEUCS]" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 245/258 [est 94 min, cumulative 81.0 h] time exp7 BIBLE EHAUSM-I"
run ./scripts/run.sh 7 --dataset bible --algo "EHAUSM-I" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 246/258 [est 243 min, cumulative 85.0 h] time exp7 BIBLE Pre-HAUSPM"
run ./scripts/run.sh 7 --dataset bible --algo "Pre-HAUSPM" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 247/258 [est 275 min, cumulative 89.6 h] time exp7 SIGN HAUSP-UB[noEUCS]"
run ./scripts/run.sh 7 --dataset sign --algo "HAUSP-UB[noEUCS]" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 248/258 [est 10 min, cumulative 89.8 h] time exp7 SIGN EHAUSM-I"
run ./scripts/run.sh 7 --dataset sign --algo "EHAUSM-I" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 249/258 [est 106 min, cumulative 91.6 h] time exp7 SIGN Pre-HAUSPM"
run ./scripts/run.sh 7 --dataset sign --algo "Pre-HAUSPM" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 250/258 [est 97 min, cumulative 93.2 h] time exp7 KOSARAK HAUSP-UB[noEUCS]"
run ./scripts/run.sh 7 --dataset kosarak --algo "HAUSP-UB[noEUCS]" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 251/258 [est 266 min, cumulative 97.6 h] time exp7 KOSARAK EHAUSM-I"
run ./scripts/run.sh 7 --dataset kosarak --algo "EHAUSM-I" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 252/258 [est 369 min, cumulative 103.8 h] time exp7 KOSARAK Pre-HAUSPM"
run ./scripts/run.sh 7 --dataset kosarak --algo "Pre-HAUSPM" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 253/258 [est 78 min, cumulative 105.1 h] time exp7 BMS1_SPMF HAUSP-UB[noEUCS]"
run ./scripts/run.sh 7 --dataset bms1_spmf --algo "HAUSP-UB[noEUCS]" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 254/258 [est 42 min, cumulative 105.8 h] time exp7 BMS1_SPMF EHAUSM-I"
run ./scripts/run.sh 7 --dataset bms1_spmf --algo "EHAUSM-I" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 255/258 [est 653 min, cumulative 116.6 h] time exp7 BMS1_SPMF Pre-HAUSPM"
run ./scripts/run.sh 7 --dataset bms1_spmf --algo "Pre-HAUSPM" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 256/258 [est 263 min, cumulative 121.0 h] time exp7 FIFA HAUSP-UB[noEUCS]"
run ./scripts/run.sh 7 --dataset fifa --algo "HAUSP-UB[noEUCS]" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 257/258 [est 1151 min, cumulative 140.2 h] time exp7 FIFA EHAUSM-I"
run ./scripts/run.sh 7 --dataset fifa --algo "EHAUSM-I" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
stop_check
echo "[batch] $(date +%H:%M) 258/258 [est 1325 min, cumulative 162.3 h] time exp7 FIFA Pre-HAUSPM"
run ./scripts/run.sh 7 --dataset fifa --algo "Pre-HAUSPM" --k 10,20,50,100 --repeats 3 --repeats-min-seconds 10 --results-dir results-2026-09l --resume
echo "[batch] $(date) done"
