#!/usr/bin/env python3
"""Generate every numeric table of the manuscript from the result CSVs.

Sources: the legacy CSVs under ``results/`` merged with the 2026-09 re-runs
under ``results-2026-09/`` according to ``common.MERGE_POLICY`` (a condition
is replaced by its re-run only when both runs measured the same arm set; the
corrected HAUSP-UB-L1 arm replaces the old L1 rows, which were L1L3
measurements). Every table starts with ``% source: <csv> run_id=...`` naming
the files and run ids behind it.

Candidate counts use ONE definition for every algorithm, "utility lists
assembled":

    new-schema rows:                               Cand as logged
    legacy rows of the baselines:                  Cand as logged (identity verified on a re-run)
    legacy rows of the HAUSP-UB arms:              taken from the counts re-run under
                                                   results-2026-09/counts/ (common.overlay_counts);
                                                   printed as -- when no re-run exists

The formula "Cand + PrunedL2 + PrunedL3" for legacy HAUSP-UB rows was tested
on a re-run (verify_count_identity.py, 2026-09-04) and refuted: it overstates
the count by the node-level share of the Layer-3 prunes, which legacy files
do not record. It is therefore never applied. "Recursed" (children recursed
into) is the logged ``Recursed`` for new HAUSP-UB rows, the legacy ``Cand``
for old HAUSP-UB rows (identity verified), and ``Cand - PrunedL2`` for the
baselines.

Thresholds, sweeps and schedules come from ``ExperimentLauncher --dump-config
json``; dataset characteristics from ``dataset_stats.py``. Nothing is typed
by hand. Ratios are printed with three significant figures.

Output: analysis_out/paper/latex/*.tex plus a byte-identical copy in
../paper/tables/ (the directory the manuscript ``\\input``s) and
tables_manifest.json listing file, label and sources of every table.

Usage: python3 analysis/build_latex_tables.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (ANALYSIS_OUT, ARM_DISPLAY, DS_ORDER, OK, PAPER_UB, PAPER_UB_L1L2, PAPER_UB_L1L3, ROOT,  # noqa: E402
                    count_identity_ok, ds_tex, fmt_sig, human, load_config, load_experiment, load_memory, ms_std,
                    source_comment)

OUT = ANALYSIS_OUT / "latex"
PAPER_TABLES = ROOT.parent / "paper" / "tables"
MANIFEST = OUT / "tables_manifest.json"
ALGO5 = ["EHAUSM-R", "EHAUSM-I", "Pre-HAUSPM", "HAUSP-UB-L1", PAPER_UB]
DISP = ARM_DISPLAY
TABLE_OPEN = r"\begin{table}[pos=!htbp]"
GEN_NOTE = "% Generated by analysis/build_latex_tables.py from the CSVs named above; do not edit by hand."

manifest: list[dict] = []
_config = None
_frames: dict[int, pd.DataFrame | None] = {}


def cfg() -> dict:
    global _config
    if _config is None:
        _config = load_config()
    return _config


def data(exp: int) -> pd.DataFrame | None:
    if exp not in _frames:
        _frames[exp] = load_experiment(exp)
    return _frames[exp]


def disp(a: str) -> str:
    return DISP.get(a, a)


def emit(name: str, label: str, lines: list[str], frames: list[pd.DataFrame | None]) -> None:
    text = "\n".join([source_comment([f for f in frames if f is not None]), GEN_NOTE] + lines) + "\n"
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(text)
    targets = [str((OUT / name).relative_to(ROOT))]
    if PAPER_TABLES.exists():
        (PAPER_TABLES / name).write_text(text)
        targets.append(str(PAPER_TABLES / name))
    manifest.append({"file": name, "label": label,
                     "sources": [f.attrs.get("source") for f in frames if f is not None],
                     "run_ids": sorted({r for f in frames if f is not None for r in (f.attrs.get("run_ids") or [])})})
    print(f"  [latex] {' , '.join(targets)}")


def table_head(caption: str, label: str, colspec: str, header: str, size: str = r"\small") -> list[str]:
    return [TABLE_OPEN, r"\centering", size, r"\renewcommand{\arraystretch}{1.15}",
            r"\caption{" + caption + "}", label, r"\begin{tabular}{" + colspec + "}", r"\toprule", header, r"\midrule"]


def table_tail(extra: list[str] | None = None) -> list[str]:
    return [r"\bottomrule"] + (extra or []) + [r"\end{tabular}", r"\end{table}"]


def bold_best(cells: list[tuple[float | None, str]], lower_is_better: bool = True) -> list[str]:
    """Wrap the best numeric cell of a group in \\textbf; non-numeric cells pass through."""
    nums = [v for v, _ in cells if v is not None and np.isfinite(v)]
    if not nums:
        return [s for _, s in cells]
    best = min(nums) if lower_is_better else max(nums)
    return [(r"\textbf{" + s + "}" if (v is not None and np.isfinite(v) and v == best) else s) for v, s in cells]


def complete_trials(g: pd.DataFrame, n_batches: int) -> list[int]:
    succ = g[g["Status"].isin(OK)]
    return [r for r in sorted(succ["RunIndex"].unique()) if len(succ[succ["RunIndex"] == r]) == n_batches]


def fail_cell(g: pd.DataFrame) -> str | None:
    f = g[g["Status"].isin(["OT", "OOM"])].sort_values(["RunIndex", "BatchID"])
    if len(f):
        r = f.iloc[0]
        return f"{r['Status']}@{int(r['BatchID'])}"
    return None


def pct(v: float) -> str:
    if not np.isfinite(v):
        return "--"
    if 0 < v < 0.05:
        return "$<$0.1"
    return f"{v:.1f}"


def thousands(v) -> str:
    return f"{int(v):,}".replace(",", "{,}")


def nsum(series) -> float:
    """Sum that stays NaN when every value is NaN (a legacy HAUSP-UB count not yet re-measured)."""
    return float(series.sum(min_count=1)) if len(series) else float("nan")


def fmt_eta(v: float) -> str:
    if v is None or not np.isfinite(v):
        return "--"
    return human(v) if v >= 1000 else f"{v:,.1f}"


# ----------------------------------------------------------------------------- tables
def tab_variance() -> None:
    rows = []
    frames = []
    for exp in (1, 2, 3, 4, 8):
        df = data(exp)
        if df is None:
            continue
        frames.append(df)
        ok = df[df["Status"].isin(OK)]
        keys = ["Dataset", "Algorithm", "MinUtil", "DeltaRatio"]
        per = ok.groupby(keys + ["RunIndex"], as_index=False).agg(t=("tTotal(ms)", "sum"))
        g = per.groupby(keys)["t"]
        cv = (g.std() / g.mean()).dropna() * 100
        ntr = g.count()
        big = cv[g.mean()[cv.index] >= 5000]
        rows.append((f"Exp.~{exp}", len(cv), f"{ntr.min()}--{ntr.max()}" if ntr.min() != ntr.max() else str(ntr.min()),
                     cv.median(), cv.quantile(0.95), big.max() if len(big) else float("nan")))
    df7 = data(7)
    if df7 is not None:
        frames.append(df7)
        ok7 = df7[df7["Status"].isin(OK)].copy()
        ok7["K"] = (1.0 / ok7["DeltaRatio"]).round().astype(int)
        per7 = ok7.groupby(["Dataset", "Algorithm", "K", "RunIndex"], as_index=False).agg(n=("BatchID", "count"), t=("tTotal(ms)", "sum"))
        per7 = per7[per7["n"] == per7["K"]]
        tri = per7.groupby(["Dataset", "Algorithm", "K"])["RunIndex"].nunique()
        full = per7.set_index(["Dataset", "Algorithm", "K"]).loc[tri[tri >= 3].index].reset_index()
        g7 = full.groupby(["Dataset", "Algorithm", "K"])["t"]
        cv7 = (g7.std() / g7.mean()).dropna() * 100
        n7 = g7.count()
        big7 = cv7[g7.mean()[cv7.index] >= 5000]
        rows.append(("Exp.~7", len(cv7), f"{n7.min()}--{n7.max()}" if len(n7) and n7.min() != n7.max() else (str(n7.min()) if len(n7) else "--"),
                     cv7.median(), cv7.quantile(0.95), big7.max() if len(big7) else float("nan")))
    lines = table_head(
        r"Run-to-run variability of total runtime: CV = std/mean per configuration; trials per configuration"
        r" (3 by default, 10 for configurations under 10\,s and 15 under 1\,s); last column: configurations with mean runtime at least 5\,s.",
        r"\label{tab:variance}", "lrrrrr",
        r"Experiment & Configs & Trials & Median CV (\%) & 95th pct.\ CV (\%) & Max CV (\%), runs $\geq$ 5\,s \\")
    for name, n, tr, med, p95, mx in rows:
        mxs = f"{mx:.1f}" if np.isfinite(mx) else "--"
        lines.append(f"{name} & {n} & {tr} & {med:.2f} & {p95:.2f} & {mxs} \\\\")
    lines += table_tail()
    emit("tab_variance.tex", "tab:variance", lines, frames)


def tab_datasets() -> None:
    stats_p = ANALYSIS_OUT / "dataset_stats.json"
    if not stats_p.exists():
        raise SystemExit("analysis_out/paper/dataset_stats.json missing: run analysis/dataset_stats.py first")
    stats = json.loads(stats_p.read_text())
    exp2 = next(e for e in cfg()["experiments"] if e["id"] == 2)
    sweeps = {r["csv_name"]: r["min_utils"] for r in exp2["runs"]}
    order = sorted([d for d in DS_ORDER if d in stats], key=lambda d: stats[d]["sequences"])
    lines = table_head(
        r"Statistical characteristics of the experimental datasets (measured from the files: sequences $|D|$,"
        r" distinct items $|I|$, mean itemsets per sequence, total utility) and the per-dataset $minUtil$ sweep of Experiment~2.",
        r"\label{tab:datasets}\label{tab:exp2_params}", "lrrrrl",
        r"Dataset & $|D|$ & $|I|$ & Avg.\ itemsets/seq.\ & Total utility & $minUtil$ sweep (\%) \\")
    for d in order:
        s = stats[d]
        sw = ";\; ".join(f"{v*100:.3f}".rstrip("0").rstrip(".") for v in sweeps.get(d, []))
        lines.append(f"{ds_tex(d)} & {thousands(s['sequences'])} & {thousands(s['items'])} & {s['avg_itemsets']:.2f} & "
                     f"{thousands(s['total_utility'])} & {sw} \\\\")
    lines += table_tail()
    # datasets table has no CSV source; record the stats file and the config dump instead
    fake = pd.DataFrame(); fake.attrs["source"] = "analysis_out/paper/dataset_stats.json;analysis_out/paper/experiment_config.json"
    fake.attrs["run_ids"] = ["measured-from-files"]
    emit("tab_datasets.tex", "tab:datasets", lines, [fake])


def tab_exp1_eta_avg() -> None:
    df = data(1)
    ok = df[df["Status"].isin(OK)].copy()
    ok = ok[ok["RunIndex"] == ok.groupby(["Dataset", "Algorithm"])["RunIndex"].transform("min")]
    ok["eta"] = ok["CandUnified"] / ok["HAUSP"].replace(0, np.nan)
    m = ok.groupby(["Dataset", "Algorithm"])["eta"].mean().unstack("Algorithm")
    lines = table_head(
        r"Mean candidate-generation efficiency $\eta = $ lists assembled$/|\mathit{HAUSP}|$ over five batches"
        r" (the same operational count for every algorithm) and the ratio $\eta(\text{EHAUSM-R})/\eta(\text{HAUSP-UB})$.",
        r"\label{tab:exp1_eta_avg}", "lrrrr",
        r"Dataset & $\eta$ EHAUSM-I & $\eta$ EHAUSM-R & $\eta$ HAUSP-UB & Ratio \\")

    for ds in DS_ORDER:
        if ds not in m.index:
            continue
        r_ = m.loc[ds]
        cells = [(r_.get(a, np.nan), fmt_eta(r_.get(a, np.nan))) for a in ["EHAUSM-I", "EHAUSM-R", PAPER_UB]]
        ub = r_.get(PAPER_UB, np.nan)
        ratio = r_["EHAUSM-R"] / ub if (np.isfinite(ub) and ub) else np.nan
        ratio_s = ("$" + fmt_sig(ratio, 3) + r"\times$") if np.isfinite(ratio) else "--"
        lines.append(ds_tex(ds) + " & " + " & ".join(bold_best(cells)) + " & " + ratio_s + r" \\")
    lines += table_tail()
    emit("tab_exp1_eta_avg.tex", "tab:exp1_eta_avg", lines, [df])


def tab_phase_breakdown() -> None:
    # Batch-level timers only (scan+flatten, mining, Layer-1 filter). The per-node Layer-2/3
    # timers were removed from the hot path on 2026-09-10: a thread CPU-time read costs more
    # than the comparison it brackets, so their columns measured the timers, not the filters.
    df = data(1)
    ok = df[df["Status"].isin(OK) & (df["Algorithm"] == PAPER_UB)]
    per = ok.groupby(["Dataset", "RunIndex"], as_index=False)[["tScan(ms)", "tMining(ms)", "tLayer1(ms)", "tTotal(ms)"]].sum()
    for c in ["tScan(ms)", "tMining(ms)", "tLayer1(ms)"]:
        per[c] = 100.0 * per[c] / per["tTotal(ms)"]
    m = per.groupby("Dataset").mean(numeric_only=True)
    lines = table_head(
        r"Phase-level runtime breakdown of HAUSP-UB (\% of total runtime over five batches, mean over trials; "
        r"batch-level timers only: the Layer-2 and Layer-3 tests are single comparisons per child and are "
        r"characterised by the counts of Table~\ref{tab:exp9_counts}, not timed).",
        r"\label{tab:phase_breakdown}", "lrrr",
        r"Dataset & Scan+flatten & Mining & L1 filter \\")
    for ds in DS_ORDER:
        if ds not in m.index:
            continue
        r_ = m.loc[ds]
        lines.append(f"{ds_tex(ds)} & {pct(r_['tScan(ms)'])} & {pct(r_['tMining(ms)'])} & {pct(r_['tLayer1(ms)'])} \\\\")
    lines += table_tail()
    emit("tab_phase_breakdown.tex", "tab:phase_breakdown", lines, [df])


def runtime_cell(g: pd.DataFrame, n_batches: int, scale: float, nd: int) -> tuple[float | None, str]:
    trials = complete_trials(g, n_batches)
    if trials:
        succ = g[g["Status"].isin(OK)]
        per = [succ[succ["RunIndex"] == r]["tTotal(ms)"].sum() / scale for r in trials]
        return float(np.mean(per)), (ms_std(per, nd=nd) if len(per) >= 3 else f"{per[0]:.{nd}f}$^{{\\dagger}}$")
    fc = fail_cell(g)
    return None, (fc if fc else "--")


def tab_exp1_runtime() -> None:
    df = data(1)
    n_b = int(df.groupby(["Dataset", "Algorithm", "RunIndex"])["BatchID"].nunique().max())
    lines = table_head(r"Total runtime (s) over five batches (mean $\pm$ std over trials; OT@$b$: time limit exceeded at batch $b$).",
                       r"\label{tab:exp1_runtime}", "l" + "r" * len(ALGO5),
                       "Dataset & " + " & ".join(disp(a) for a in ALGO5) + r" \\")
    for ds in DS_ORDER:
        cells = [runtime_cell(df[(df["Dataset"] == ds) & (df["Algorithm"] == a)], n_b, 1000.0, 1) for a in ALGO5]
        lines.append(ds_tex(ds) + " & " + " & ".join(bold_best(cells)) + r" \\")
    lines += table_tail()
    emit("tab_exp1_runtime.tex", "tab:exp1_runtime", lines, [df])


def tab_exp2_pruned() -> None:
    df = data(2)
    variants = ["EHAUSM-I", "HAUSP-UB-L1", PAPER_UB_L1L3, PAPER_UB_L1L2, PAPER_UB]
    exp2 = next(e for e in cfg()["experiments"] if e["id"] == 2)
    n_sweep = {r["csv_name"]: len(r["min_utils"]) for r in exp2["runs"]}
    ok = df[df["Status"].isin(OK)]
    ok = ok[ok["RunIndex"] == ok.groupby(["Dataset", "Algorithm", "MinUtil"])["RunIndex"].transform("min")]
    lines = table_head(
        r"Ablation of the pruning layers, summed over the $minUtil$ sweep (counts are deterministic across trials):"
        r" candidates rejected by each layer, utility lists assembled (the same count for every algorithm), and"
        r" children recursed into. HAUSP-UB$^{L1}$ = Layer~1 only; HAUSP-UB$^{L1L3}$ = Layers 1+3; HAUSP-UB$^{L1L2}$ = Layers 1+2;"
        r" all variants without the EUCS pre-filter (decision of 2026-09-09). A superscript $k/n$ marks a variant that"
        r" completed only $k$ of the $n$ thresholds (the others exceeded the time limit); its sums cover those $k$"
        r" thresholds only. Compact units (K/M/B).",
        r"\label{tab:exp2_pruning}", "llrrrrr",
        r"Dataset & Variant & L1 (SWU) & L2 (IAUUB) & L3 (SeqMFUUB) & Lists assembled & Recursed \\", size=r"\scriptsize")
    first_block = True
    for ds in DS_ORDER:
        block = []
        for a in variants:
            g = ok[(ok["Dataset"] == ds) & (ok["Algorithm"] == a)]
            if len(g) == 0:
                fc = fail_cell(df[(df["Dataset"] == ds) & (df["Algorithm"] == a)])
                if fc:
                    block.append(f" & {disp(a)} & \\multicolumn{{5}}{{l}}{{{fc} at every threshold}} \\\\")
                continue
            k, n = g["MinUtil"].nunique(), n_sweep.get(ds, g["MinUtil"].nunique())
            name = disp(a) + (f"$^{{{k}/{n}}}$" if k < n else "")
            block.append(f" & {name} & {human(g['PrunedL1(SWU)'].sum())} & {human(g['PrunedL2(IAUUB)'].sum())} & "
                         f"{human(g['PrunedL3(MFUUB)'].sum())} & {human(nsum(g['CandUnified']))} & {human(nsum(g['RecursedUnified']))} \\\\")
        if not block:
            continue
        if not first_block:
            lines.append(r"\addlinespace")
        first_block = False
        block[0] = ds_tex(ds) + block[0]
        lines += block
    lines += table_tail()
    emit("tab_exp2_pruned.tex", "tab:exp2_pruning", lines, [df])


def tab_exp3_delta20() -> None:
    df = data(3)
    mem = load_memory(3)
    ok = df[df["Status"].isin(OK)]
    d20 = float(cfg()["exp3_deltas"][-1])
    b1 = ok[(ok["DeltaRatio"].round(3) == round(d20, 3)) & (ok["BatchID"] == 1)]
    m1 = (mem[mem["Status"].isin(OK) & (mem["DeltaRatio"].round(3) == round(d20, 3)) & (mem["BatchID"] == 1)]
          if mem is not None else pd.DataFrame())
    algos = ["EHAUSM-R", "EHAUSM-I", "Pre-HAUSPM", PAPER_UB]
    lines = table_head(
        rf"Update processing at $\delta = {int(round(d20*100))}\%$ (batch~1): update time is mean $\pm$ std over trials;"
        r" update memory is the peak live heap of the update batch (used heap after a forced full collection, dedicated"
        r" memory run, one JVM per arm); update candidates are lists assembled (deterministic). Bold marks the best value"
        r" per dataset and metric; --: not measured.",
        r"\label{tab:exp3_delta20}", "llrrr",
        r"Dataset & Algorithm & Update $t$ (s) & Update mem.\ (MB) & Update cand. \\")
    first_block = True
    for ds in DS_ORDER:
        rows = []
        for a in algos:
            g = b1[(b1["Dataset"] == ds) & (b1["Algorithm"] == a)]
            if len(g) == 0:
                continue
            t = [g[g["RunIndex"] == r]["tTotal(ms)"].sum() / 1000 for r in sorted(g["RunIndex"].unique())]
            gm = m1[(m1["Dataset"] == ds) & (m1["Algorithm"] == a)] if len(m1) else pd.DataFrame()
            m = [gm[gm["RunIndex"] == r]["MemLive(MB)"].max() for r in sorted(gm["RunIndex"].unique())] if len(gm) else []
            mcell = (float(np.mean(m)), ms_std(m, nd=0)) if m else (None, "--")
            c = nsum(g[g["RunIndex"] == g["RunIndex"].min()]["CandUnified"])
            rows.append((a, (float(np.mean(t)), ms_std(t, nd=1)), mcell, (c, human(c))))
        if not rows:
            continue
        if not first_block:
            lines.append(r"\addlinespace")
        first_block = False
        tc = bold_best([r[1] for r in rows]); mc = bold_best([r[2] for r in rows]); cc = bold_best([r[3] for r in rows])
        for i, r in enumerate(rows):
            lines.append((ds_tex(ds) if i == 0 else "") + f" & {disp(r[0])} & {tc[i]} & {mc[i]} & {cc[i]} \\\\")
    lines += table_tail()
    emit("tab_exp3_delta20.tex", "tab:exp3_delta20", lines, [df, mem])


def tab_exp4_memory() -> None:
    """Peak live heap per arm from the dedicated memory runs (MemMode=live).

    The legacy used-heap column (results/exp4, sampled under lazy GC) is not
    used: it depends on the heap history of the JVM (see EXPERIMENT_CHANGELOG,
    2026-09-05). Failure cells come from the timing run of Exp 4 when the
    memory run has no row for the arm.
    """
    mem = load_memory(4)
    timing = data(4)
    n_b = int(timing.groupby(["Dataset", "Algorithm", "RunIndex"])["BatchID"].nunique().max())
    lines = table_head(
        r"Peak live heap (MB) over five update batches: used heap right after a forced full collection, sampled"
        r" every second and at the end of each batch, one JVM per arm (mean $\pm$ std over trials;"
        r" OT@$b$ / OOM@$b$: run stopped at batch $b$; --: not measured).",
        r"\label{tab:exp4_memory}", "l" + "r" * len(ALGO5),
        "Dataset & " + " & ".join(disp(a) for a in ALGO5) + r" \\")
    for ds in DS_ORDER:
        cells = []
        for a in ALGO5:
            g = mem[(mem["Dataset"] == ds) & (mem["Algorithm"] == a)] if mem is not None else pd.DataFrame()
            trials = complete_trials(g, n_b) if len(g) else []
            if trials:
                succ = g[g["Status"].isin(OK)]
                per = [succ[succ["RunIndex"] == r]["MemLive(MB)"].max() for r in trials]
                cells.append((float(np.mean(per)), ms_std(per, nd=0)))
            else:
                fc = fail_cell(g) if len(g) else None
                if fc is None:
                    fc = fail_cell(timing[(timing["Dataset"] == ds) & (timing["Algorithm"] == a)])
                cells.append((None, fc if fc else "--"))
        lines.append(ds_tex(ds) + " & " + " & ".join(bold_best(cells)) + r" \\")
    lines += table_tail()
    emit("tab_exp4_memory.tex", "tab:exp4_memory", lines, [mem, timing])


def tab_exactness() -> None:
    d5 = data(5)
    d6 = data(6)
    ok5 = d5[d5["Status"].isin(OK)]
    piv = ok5.pivot_table(index=["Dataset", "MinUtil"], columns="Algorithm", values="HAUSP", aggfunc="first").reset_index()
    if PAPER_UB not in piv.columns:
        piv[PAPER_UB] = np.nan
    lines = [TABLE_OPEN, r"\centering", r"\small", r"\renewcommand{\arraystretch}{1.15}",
             r"\caption{Exactness verification against the EHAUSM-R oracle: (a) HAUSP-set comparison on a single batch;"
             r" (b) HAUSP counts at every batch across five consecutive update batches (identical for oracle and HAUSP-UB).}",
             r"\label{tab:exactness}", r"(a)\\[3pt]", r"\begin{tabular}{lcrrr}", r"\toprule",
             r"Dataset & $minUtil$ (\%) & HAUSP (Oracle) & HAUSP (UB) & Deviation \\", r"\midrule"]
    first_ds = True
    for ds in DS_ORDER:
        sub = piv[piv["Dataset"] == ds].sort_values("MinUtil", ascending=False)
        if len(sub) == 0:
            continue
        if not first_ds:
            lines.append(r"\midrule")
        first_ds = False
        for i, (_, r_) in enumerate(sub.iterrows()):
            mu = f"{r_['MinUtil']*100:.3f}".rstrip("0").rstrip(".")
            head = (r"\multirow{" + str(len(sub)) + "}{*}{" + ds_tex(ds) + "}") if i == 0 else ""
            if np.isfinite(r_[PAPER_UB]):
                dev = int(r_[PAPER_UB] - r_["EHAUSM-R"])
                lines.append(f"{head} & {mu} & {thousands(r_['EHAUSM-R'])} & {thousands(r_[PAPER_UB])} & {dev} \\\\")
            else:
                lines.append(f"{head} & {mu} & {thousands(r_['EHAUSM-R'])} & -- & -- \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", "", r"\vspace{8pt}", r"(b)\\[3pt]",
              r"\begin{tabular}{lcrrrrr}", r"\toprule",
              r"Dataset & $minUtil$ (\%) & Batch 0 & Batch 1 & Batch 2 & Batch 3 & Batch 4 \\", r"\midrule"]
    d6 = d6[d6["Dataset"].astype(str).str.lower() != "example"].copy()
    if "UBArm" in d6.columns:
        d6 = d6[d6["UBArm"].fillna("HAUSP-UB") == PAPER_UB]
    name_map = {"bible": "BIBLE", "bms1_spmf": "BMS1_SPMF", "fifa": "FIFA", "kosarak": "KOSARAK",
                "leviathan": "LEVIATHAN", "sign": "SIGN", "syn_c8t1s5i8n5k": "C8T1S5I8N5K", "c8t1s5i8n5k": "C8T1S5I8N5K"}
    d6["DS"] = d6["Dataset"].astype(str).str.lower().map(name_map).fillna(d6["Dataset"])
    cols = [c for c in d6.columns if c.startswith("HAUSP_")]
    for ds in DS_ORDER:
        sub = d6[(d6["DS"] == ds) & (d6["Status"] == "SUCCESS_MATCH")].sort_values("BatchID")
        if len(sub) == 0:
            continue
        sub = sub[sub["RunIndex"] == sub["RunIndex"].min()]
        mu = f"{sub['MinUtil'].iloc[0]*100:.3f}".rstrip("0").rstrip(".")
        assert (sub[cols[0]] == sub[cols[1]]).all(), f"exp6 mismatch on {ds}"
        lines.append(ds_tex(ds) + " & " + mu + " & " + " & ".join(thousands(v) for v in sub[cols[0]]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    emit("tab_exactness.tex", "tab:exactness", lines, [d5, d6])


def tab_exp7_matrix() -> None:
    df = data(7)
    d11 = data(11)
    ks = [int(k) for k in cfg()["exp7_batch_counts"]]
    algos = [PAPER_UB, "EHAUSM-I", "Pre-HAUSPM"]
    df = df.copy()
    df["K"] = (1.0 / df["DeltaRatio"]).round().astype(int)
    warm_note = ""
    if d11 is not None and len(d11):
        d11 = d11.copy()
        d11["K"] = d11.groupby(["Dataset", "Algorithm", "RunIndex"])["BatchID"].transform("count")
        first = float(cfg()["warm_start_first_ratio"]) * 100
        warm_note = (rf" Rows marked \emph{{warm20}} use the warm-start schedule of Experiment~11: batch~0 holds {first:.0f}\% of the data"
                     r" and the remaining $K{-}1$ batches share the rest equally; every other row uses $K$ equal batches.")
    lines = table_head(
        r"Total runtime (min) for $K$ batches with the total data volume held fixed (mean $\pm$ std over trials;"
        r" $\dagger$: single trial under the uniform rule; OT@$b$ / OOM@$b$: limit exceeded at batch $b$)." + warm_note,
        r"\label{tab:exp7_matrix}", "llrrrr",
        "Dataset & Algorithm & " + " & ".join(f"$K{{=}}{k}$" for k in ks) + r" \\")
    first_block = True

    def block_for(frame, ds, label):
        rows = {a: [] for a in algos}
        for k in ks:
            col = []
            for a in algos:
                g = frame[(frame["Dataset"] == ds) & (frame["Algorithm"] == a) & (frame["K"] == k)]
                col.append(runtime_cell(g, k, 60000.0, 1) if len(g) else (None, "--"))
            for a, c in zip(algos, bold_best(col)):
                rows[a].append(c)
        out = []
        for i, a in enumerate(algos):
            out.append((label if i == 0 else "") + f" & {disp(a)} & " + " & ".join(rows[a]) + r" \\")
        return out

    for ds in DS_ORDER:
        if len(df[df["Dataset"] == ds]) == 0:
            continue
        if not first_block:
            lines.append(r"\addlinespace")
        first_block = False
        lines += block_for(df, ds, ds_tex(ds))
        if d11 is not None and len(d11[d11["Dataset"] == ds]):
            lines.append(r"\addlinespace")
            lines += block_for(d11, ds, ds_tex(ds) + r" (\emph{warm20})")
    lines += table_tail()
    emit("tab_exp7_matrix.tex", "tab:exp7_matrix", lines, [df, d11])


def tab_exp8_eta() -> None:
    df = data(8)
    ok = df[df["Status"].isin(OK)].copy()
    ok = ok[ok["RunIndex"] == ok.groupby(["Dataset", "Algorithm", "MinUtil"])["RunIndex"].transform("min")]
    ok["eta"] = ok["CandUnified"] / ok["HAUSP"].replace(0, np.nan)
    lines = table_head(
        r"Candidate-generation efficiency $\eta = $ lists assembled$/|\mathit{HAUSP}|$ as $minUtil$ approaches each dataset's"
        r" noise floor; $|\mathit{HAUSP}|$ is the pattern count at that threshold; ratio $= \eta(\text{EHAUSM-I})/\eta(\text{HAUSP-UB})$.",
        r"\label{tab:exp8_eta}", "lrrrrr",
        r"Dataset & $minUtil$ (\%) & $|\mathit{HAUSP}|$ & $\eta$ EHAUSM-I & $\eta$ HAUSP-UB & Ratio \\")

    first_block = True
    for ds in DS_ORDER:
        sub = ok[ok["Dataset"] == ds]
        if len(sub) == 0:
            continue
        if not first_block:
            lines.append(r"\addlinespace")
        first_block = False
        for i, mu in enumerate(sorted(sub["MinUtil"].unique(), reverse=True)):
            r = sub[sub["MinUtil"] == mu]
            e_i = float(r[r["Algorithm"] == "EHAUSM-I"]["eta"].mean())
            ru = r[r["Algorithm"] == PAPER_UB]
            e_u = float(ru["eta"].mean()) if len(ru) else np.nan
            h = int(r["HAUSP"].iloc[0])
            ratio = e_i / e_u if (np.isfinite(e_u) and e_u and np.isfinite(e_i)) else np.nan
            cells = bold_best([(e_i, fmt_eta(e_i)), (e_u, fmt_eta(e_u))])
            ratio_s = (fmt_sig(ratio, 3) + "$\\times$") if np.isfinite(ratio) else "--"
            mu_pct = f"{mu*100:.3f}".rstrip("0").rstrip(".")
            lines.append((ds_tex(ds) if i == 0 else "") + f" & {mu_pct} & {human(h)} & {cells[0]} & {cells[1]} & {ratio_s} \\\\")
    lines += table_tail()
    emit("tab_exp8_eta.tex", "tab:exp8_eta", lines, [df])


EXP9_ARMS = [("EHAUSM-I", "persistent tree, coupled bound at node, fresh lists (reference)"),
             ("EHAUSM-R", "no retention: re-mine each batch"),
             ("HAUSP-UB[noL2+L3@node+nopool]", "flat arrays, EUCS matrices, item-level SWU test"),
             ("HAUSP-UB[noL2+nopool]", "coupled bound tested on the child before recursion"),
             ("HAUSP-UB[noL2]", "shared list pool"),
             ("HAUSP-UB", "decoupled estimate during assembly (Layer~2)"),
             ("HAUSP-UB[noL2+noEUCS]", "as UB+pool but without the EUCS pre-filter"),
             ("HAUSP-UB[noEUCS]", "as the full algorithm but without the EUCS pre-filter")]
EXP9_SHORT = {"EHAUSM-I": "EHAUSM-I", "EHAUSM-R": "EHAUSM-R",
              "HAUSP-UB[noL2+L3@node+nopool]": r"UB$_{\mathrm{layout}}$",
              "HAUSP-UB[noL2+nopool]": r"UB$_{\mathrm{+child}}$",
              "HAUSP-UB[noL2]": r"UB$_{\mathrm{+pool}}$", "HAUSP-UB": r"UB$_{\mathrm{+L2}}$ (HAUSP-UB$_{\mathrm{EUCS}}$)",
              "HAUSP-UB[noL2+noEUCS]": r"UB$_{\mathrm{+pool}}$ $-$ EUCS", "HAUSP-UB[noEUCS]": r"UB full $-$ EUCS (HAUSP-UB)"}


def tab_exp9_attribution() -> None:
    """Runtime per dataset for the six attribution arms; each arm adds one decision to the previous one."""
    df = data(9)
    lines = table_head(
        r"Attribution of the runtime gap: total runtime (s) over the five batches of Experiment~1, mean of three"
        r" trials, one JVM per arm. Each arm adds exactly one design decision to the arm above it:"
        r" EHAUSM-I (persistent tree, coupled bound tested on node entry) $\to$ EHAUSM-R (no retention)"
        r" $\to$ UB$_{\mathrm{layout}}$ (flat arrays, EUCS matrices, item-level SWU test)"
        r" $\to$ UB$_{\mathrm{+child}}$ (coupled bound tested on the child before recursion)"
        r" $\to$ UB$_{\mathrm{+pool}}$ (shared list pool) $\to$ UB$_{\mathrm{+L2}}$ (decoupled estimate during"
        r" assembly; the configuration with EUCS, HAUSP-UB$_{\mathrm{EUCS}}$) $\to$ $-$ EUCS (the co-occurrence"
        r" pre-filter neither built nor consulted; the algorithm of this paper, HAUSP-UB). All arms return"
        r" identical pattern sets. Bold: fastest arm per dataset.",
        r"\label{tab:attribution}", "l" + "r" * len(DS_ORDER),
        "Arm & " + " & ".join(ds_tex(d) for d in DS_ORDER) + r" \\", size=r"\small")
    if df is None:
        for a, _ in EXP9_ARMS:
            lines.append(EXP9_SHORT[a] + " & " + " & ".join(["--"] * len(DS_ORDER)) + r" \\")
    else:
        ok = df[df["Status"].isin(OK)]
        per = ok.groupby(["Dataset", "Algorithm", "RunIndex"])["tTotal(ms)"].sum().div(1000)
        m = per.groupby(["Dataset", "Algorithm"]).agg(["mean", "std"])
        cells = {ds: [] for ds in DS_ORDER}
        for a, _ in EXP9_ARMS:
            for ds in DS_ORDER:
                if (ds, a) in m.index:
                    mu, sd = m.loc[(ds, a), "mean"], m.loc[(ds, a), "std"]
                    vals = per.loc[(ds, a)].tolist()
                    cells[ds].append((float(mu), ms_std(vals, nd=1)))
                else:
                    cells[ds].append((None, "--"))
        bolded = {ds: bold_best(cells[ds]) for ds in DS_ORDER}
        for i, (a, _) in enumerate(EXP9_ARMS):
            lines.append(EXP9_SHORT[a] + " & " + " & ".join(bolded[ds][i] for ds in DS_ORDER) + r" \\")
    lines += table_tail()
    emit("tab_exp9_attribution.tex", "tab:attribution", lines, [df])


def tab_exp9_counts() -> None:
    """Lists assembled and children recursed into per arm and dataset (deterministic, trial 0)."""
    df = data(9)
    lines = table_head(
        r"Search-tree size behind Table~\ref{tab:attribution} (trial~1, summed over five batches, compact units):"
        r" utility lists assembled and children recursed into. From UB$_{\mathrm{layout}}$ to UB$_{\mathrm{+L2}}$ every"
        r" arm assembles the same lists, and the two arms without EUCS assemble exactly the lists of EHAUSM-R;"
        r" testing the coupled bound on the child (UB$_{\mathrm{+child}}$) is what stops the search from entering"
        r" rejected children as nodes, and Layer~2 changes neither count.",
        r"\label{tab:attribution_counts}", "ll" + "r" * len(DS_ORDER),
        "Arm & Count & " + " & ".join(ds_tex(d) for d in DS_ORDER) + r" \\", size=r"\scriptsize")
    if df is not None:
        ok = df[df["Status"].isin(OK)]
        ok = ok[ok["RunIndex"] == ok.groupby(["Dataset", "Algorithm"])["RunIndex"].transform("min")]
        agg = ok.groupby(["Dataset", "Algorithm"])[["CandUnified", "RecursedUnified"]].sum()
        for a, _ in EXP9_ARMS:
            for col, label in (("CandUnified", "lists"), ("RecursedUnified", "recursed")):
                row = [human(agg.loc[(ds, a), col]) if (ds, a) in agg.index else "--" for ds in DS_ORDER]
                lines.append((EXP9_SHORT[a] if col == "CandUnified" else "") + f" & {label} & " + " & ".join(row) + r" \\")
            lines.append(r"\addlinespace")
        if lines[-1] == r"\addlinespace":
            lines.pop()
    lines += table_tail()
    emit("tab_exp9_counts.tex", "tab:attribution_counts", lines, [df])


def tab_exp10_mu() -> None:
    df = data(10)
    mus = [float(m) for m in cfg()["mu_sweep"]]
    d20 = float(cfg()["exp3_deltas"][-1])
    lines = table_head(
        rf"Pre-HAUSPM under the safety margin $\mu \in \{{{', '.join(f'{m:.2f}' for m in mus)}\}}$ at $\delta = {int(round(d20*100))}\%$"
        r" (Experiment 3 setting): update time in seconds (mean $\pm$ std over trials); \emph{rescan}: whether the update batch"
        r" triggered a rescan for every $\mu$; last column: smallest ratio over $\mu$ of the tested buffer to the safety value"
        r" $f$ (a ratio above 1 means the bound was violated).",
        r"\label{tab:exp10_mu}", "l" + "r" * len(mus) + "cr",
        "Dataset & " + " & ".join(rf"$\mu{{=}}{m:.2f}$" for m in mus) + r" & Rescan & $\min_\mu$ tested$/f$ \\")
    for ds in DS_ORDER:
        cells = []
        resc = []
        ratios = []
        for m in mus:
            g = df[(df["Dataset"] == ds) & (df["mu"].round(3) == round(m, 3)) & (df["BatchID"] == 1)] if df is not None else pd.DataFrame()
            ok = g[g["Status"].isin(OK)] if len(g) else g
            if len(ok):
                t = [ok[ok["RunIndex"] == r]["tTotal(ms)"].sum() / 1000 for r in sorted(ok["RunIndex"].unique())]
                cells.append(ms_std(t, nd=1))
                resc.append(bool((ok["RescanTriggered"] == 1).all()))
                fvals = ok["SafetyBound"].astype(float)
                tested = ok["BufferTested"].astype(float)
                ratios.append(float((tested / fvals.replace(0, np.nan)).min()))
            else:
                fc = fail_cell(g) if len(g) else None
                cells.append(fc if fc else "--")
        if not cells or all(c == "--" for c in cells):
            lines.append(ds_tex(ds) + " & " + " & ".join(cells or ["--"] * len(mus)) + r" & -- & -- \\")
            continue
        rs = "yes" if resc and all(resc) else ("no" if resc else "--")
        rt = fmt_sig(min(ratios), 3) if ratios and np.isfinite(min(ratios)) else "--"
        lines.append(ds_tex(ds) + " & " + " & ".join(cells) + f" & {rs} & {rt} \\\\")
    lines += table_tail()
    emit("tab_exp10_mu.tex", "tab:exp10_mu", lines, [df])


def prose_numbers() -> None:
    """Derived numbers quoted in prose (handbook 3.4.8b), with their sources, as JSON."""
    out = {}
    d1 = data(1)
    hu = d1[(d1["Algorithm"] == PAPER_UB) & d1["Status"].isin(OK)]
    if len(hu):
        out["exp1_pool"] = {"PoolBorrows_min": int(hu.groupby(["Dataset", "RunIndex"])["PoolBorrows"].sum().min()),
                            "PoolBorrows_max": int(hu.groupby(["Dataset", "RunIndex"])["PoolBorrows"].sum().max()),
                            "PoolPeakLive_max": int(hu["PoolPeakLive"].max()),
                            "reuse_share": float(hu["PoolReuses"].sum() / max(1, hu["PoolBorrows"].sum())),
                            "source": d1.attrs.get("source")}
    else:
        out["exp1_pool"] = {"note": f"no rows for {PAPER_UB} in Exp 1 yet"}
    d2 = data(2)
    ok2 = d2[d2["Status"].isin(OK) & (d2["RunIndex"] == 0)]
    out["exp2_bible"] = {a: {"lists_assembled": (lambda v: None if not np.isfinite(v) else int(v))(nsum(ok2[(ok2["Dataset"] == "BIBLE") & (ok2["Algorithm"] == a)]["CandUnified"])),
                             "recursed": (lambda v: None if not np.isfinite(v) else int(v))(nsum(ok2[(ok2["Dataset"] == "BIBLE") & (ok2["Algorithm"] == a)]["RecursedUnified"]))}
                        for a in ["EHAUSM-I", "HAUSP-UB-L1", PAPER_UB_L1L3, PAPER_UB_L1L2, PAPER_UB]
                        if len(ok2[(ok2["Dataset"] == "BIBLE") & (ok2["Algorithm"] == a)])}
    out["exp2_bible"]["source"] = d2.attrs.get("source")
    exact = 0
    for e in (1, 3, 4, 7):
        d = data(e)
        ok = d[d["Status"].isin(OK) & (d["RunIndex"] == 0)]
        exact += int(ok.groupby(["Dataset", "BatchID", "MinUtil", "DeltaRatio"]).ngroups)
    out["completed_configs_exp1347_trial0"] = exact
    for e, key in ((7, "exp7_fifa_k100_live_peak_mb"), (11, "exp11_live_peak_mb")):
        mem = load_memory(e)
        if mem is not None:
            ok = mem[mem["Status"].isin(OK)]
            out[key] = {f"{ds}|{a}": float(g["MemLive(MB)"].max())
                        for (ds, a), g in ok.groupby(["Dataset", "Algorithm"])}
            out[key]["source"] = mem.attrs.get("source")
    p = ANALYSIS_OUT / "prose_numbers.json"
    p.write_text(json.dumps(out, indent=1))
    print(f"  [json]  {p.relative_to(ROOT)}")


def main() -> int:
    ok, reason = count_identity_ok()
    print(f"count identity: {reason}")
    if not ok:
        print("Tables that read legacy HAUSP-UB counts cannot be generated until analysis/verify_count_identity.py passes; nothing written.")
        return 1
    for fn in (tab_variance, tab_datasets, tab_exp1_eta_avg, tab_phase_breakdown, tab_exp1_runtime,
               tab_exp2_pruned, tab_exp3_delta20, tab_exp4_memory, tab_exactness, tab_exp7_matrix,
               tab_exp8_eta, tab_exp9_attribution, tab_exp9_counts, tab_exp10_mu, prose_numbers):
        fn()
    MANIFEST.write_text(json.dumps(manifest, indent=1))
    print(f"  [json]  {MANIFEST.relative_to(ROOT)}  ({len(manifest)} tables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
