#!/usr/bin/env python3
"""Gate: every generated numeric table must reach the manuscript through \\input.

Checks, over the tables listed in analysis_out/paper/latex/tables_manifest.json:

  1. the manuscript ``\\input``s ``tables/<file>`` for every generated table
     (comment regions of the .tex are removed before scanning);
  2. no generated table label (``\\label{tab:...}``) still appears inside the
     manuscript body itself, i.e. no hand-pasted copy survives;
  3. the copy under paper/tables/ is byte-identical to the generated file;
  4. no ``.tex`` file exists in paper/tables/ that the manuscript does not
     ``\\input`` (dead file).

Prints the ratio "tables input / tables generated" and exits non-zero when it
is below 100% or any other check fails. ``--self-test`` injects the four
faults into a temporary copy and verifies that each one is caught.

Usage: python3 analysis/check_inputs.py [--tex ../paper/HAUSP-UB-V1.tex] [--self-test]
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ANALYSIS_OUT, ROOT  # noqa: E402

LATEX_DIR = ANALYSIS_OUT / "latex"
MANIFEST = LATEX_DIR / "tables_manifest.json"
DEFAULT_TEX = ROOT.parent / "paper" / "HAUSP-UB-V1.tex"


def strip_comments(tex: str) -> str:
    """Remove ``%`` comments (keeping ``\\%``) so that commented-out code is not counted."""
    out = []
    for line in tex.splitlines():
        i = 0
        while True:
            j = line.find("%", i)
            if j < 0:
                out.append(line)
                break
            if j > 0 and line[j - 1] == "\\":
                i = j + 1
                continue
            out.append(line[:j])
            break
    return "\n".join(out)


def run_checks(tex_path: Path, tables_dir: Path, manifest: list[dict], verbose: bool = True) -> list[str]:
    problems: list[str] = []
    body = strip_comments(tex_path.read_text(encoding="utf-8"))
    inputs = set()
    for m in re.finditer(r"\\input\{([^}]*)\}", body):
        p = m.group(1).strip()
        if not p.endswith(".tex"):
            p += ".tex"
        inputs.add(p)
    generated = {t["file"] for t in manifest}
    n_ok = 0
    for t in manifest:
        f, label = t["file"], t["label"]
        rel = f"tables/{f}"
        if rel in inputs:
            n_ok += 1
        else:
            problems.append(f"not \\input: {rel} (label {label})")
        if re.search(r"\\label\{" + re.escape(label) + r"\}", body):
            problems.append(f"hand-pasted copy still in manuscript body: \\label{{{label}}}")
        src, dst = LATEX_DIR / f, tables_dir / f
        if not dst.exists():
            problems.append(f"missing in {tables_dir}: {f}")
        elif src.read_bytes() != dst.read_bytes():
            problems.append(f"paper copy differs from generated file: {f}")
    for dead in sorted(p.name for p in tables_dir.glob("*.tex")):
        if f"tables/{dead}" not in inputs:
            problems.append(f"dead file in {tables_dir}: {dead} is not \\input by the manuscript")
        elif dead not in generated:
            problems.append(f"{dead} is \\input but not generated by build_latex_tables.py (hand-made table?)")
    if verbose:
        print(f"tables generated: {len(manifest)}; \\input by {tex_path.name}: {n_ok}  "
              f"({100.0 * n_ok / max(1, len(manifest)):.0f}%)")
        for t in manifest:
            flag = "OK " if f"tables/{t['file']}" in inputs else "NO "
            print(f"  {flag} {t['file']:<28} {t['label']}")
    return problems


def self_test(tex_path: Path, tables_dir: Path, manifest: list[dict]) -> int:
    """Inject each fault into a temporary copy and require the checker to catch it."""
    if not manifest:
        print("self-test needs a manifest with at least one table")
        return 1
    caught = 0
    total = 4
    t0 = manifest[0]["file"]
    label0 = manifest[0]["label"]
    with tempfile.TemporaryDirectory() as tmp:
        tmpd = Path(tmp)
        tab = tmpd / "tables"
        shutil.copytree(tables_dir, tab)
        tex = tmpd / "paper.tex"
        base = tex_path.read_text(encoding="utf-8")
        # fault 1: \input removed (commented out)
        tex.write_text(base.replace(f"\\input{{tables/{t0}}}", f"% \\input{{tables/{t0}}}"))
        caught += any("not \\input" in p for p in run_checks(tex, tab, manifest, verbose=False))
        # fault 2: hand-pasted copy with the same label present
        tex.write_text(base + f"\n\\begin{{table}}\\label{{{label0}}}\\end{{table}}\n")
        caught += any("hand-pasted" in p for p in run_checks(tex, tab, manifest, verbose=False))
        # fault 3: paper copy edited by hand
        tex.write_text(base)
        (tab / t0).write_text((tab / t0).read_text() + "% edited\n")
        caught += any("differs" in p for p in run_checks(tex, tab, manifest, verbose=False))
        shutil.copy(LATEX_DIR / t0, tab / t0)
        # fault 4: dead file
        (tab / "tab_dead_zz.tex").write_text("% dead\n")
        caught += any("dead file" in p for p in run_checks(tex, tab, manifest, verbose=False))
    print(f"self-test: {caught}/{total} injected faults caught")
    return 0 if caught == total else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tex", default=str(DEFAULT_TEX))
    ap.add_argument("--tables-dir", default=None, help="directory the manuscript \\input's (default: <tex dir>/tables)")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    tex_path = Path(args.tex)
    tables_dir = Path(args.tables_dir) if args.tables_dir else tex_path.parent / "tables"
    if not MANIFEST.exists():
        print(f"ERROR: {MANIFEST} missing; run analysis/build_latex_tables.py first")
        return 2
    manifest = json.loads(MANIFEST.read_text())
    if not tex_path.exists():
        print(f"ERROR: manuscript {tex_path} not found")
        return 2
    if args.self_test:
        return self_test(tex_path, tables_dir, manifest)
    problems = run_checks(tex_path, tables_dir, manifest)
    if problems:
        print("FAIL:")
        for p in problems:
            print("  -", p)
        return 1
    print("PASS: every generated table is \\input, none is hand-pasted, copies are byte-identical, no dead files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
