#!/usr/bin/env python3
"""Generate the default-parameter table of README.md from the sources.

Every constant that changes a recorded number is declared once, in code, and this
script copies it into the README between the two markers. Typing the table by hand
would let it drift the moment a constant changes, and a drifted table is worse than
no table: a reader cannot tell it is stale.

    python3 analysis/default_parameters.py            # rewrite the table in README.md
    python3 analysis/default_parameters.py --check    # exit 1 if README is out of date
    python3 analysis/default_parameters.py --print    # print the table, touch nothing

--check is meant to run with the other checks before a release.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "<!-- BEGIN default-parameters (generated by analysis/default_parameters.py) -->"
END = "<!-- END default-parameters -->"

# label, file, regex capturing the value in group 1, what it controls
SPEC = [
    ("`REPEATS`", "src/main/java/ExperimentConfig.java",
     r"public static int REPEATS = ([^;]+);",
     "Trials per configuration; the CSV keeps every trial. `--repeats N`."),
    ("`REPEATS_MIN_SECONDS`", "src/main/java/ExperimentConfig.java",
     r"public static double REPEATS_MIN_SECONDS = ([^;]+);",
     "0 disables adaptive repeats. `--repeats-min-seconds S` raises the trial count for short configurations."),
    ("`RESULTS_DIR`", "src/main/java/ExperimentConfig.java",
     r'public static String RESULTS_DIR = "([^"]+)"',
     "Fallback only. The launcher, given no `--results-dir DIR`, opens "
     "`results-<run id>-<commit>` instead, so a run never writes into a tree that already holds results."),
    ("`TIMEOUT_OVERRIDE_MIN`", "src/main/java/ExperimentConfig.java",
     r"public static long TIMEOUT_OVERRIDE_MIN = ([^;]+);",
     "0 keeps each experiment's own limit. `--timeout MIN` overrides it for every batch."),
    ("`MEM_MODE_LIVE`", "src/main/java/ExperimentConfig.java",
     r"public static boolean MEM_MODE_LIVE = ([^;]+);",
     "false records the used heap; `--mem-mode live` forces a collection before each sample and needs a separate results directory."),
    ("`MU_PRELARGE`", "src/main/java/ExperimentConfig.java",
     r"public static final double MU_PRELARGE = ([^;]+);",
     "Pre-large ratio used by every experiment that does not sweep it."),
    ("`MU_SWEEP`", "src/main/java/ExperimentConfig.java",
     r"public static final double\[\] MU_SWEEP = \{([^}]+)\}",
     "Pre-large ratios swept by the opt-in study."),
    ("`EXP3_DELTAS`", "src/main/java/ExperimentConfig.java",
     r"public static final double\[\] EXP3_DELTAS = \{([^}]+)\}",
     "Increment sizes, as a fraction of the database."),
    ("`EXP7_BATCH_COUNTS`", "src/main/java/ExperimentConfig.java",
     r"public static final int\[\] EXP7_BATCH_COUNTS = \{([^}]+)\}",
     "Numbers of batches the database is split into."),
    ("`EXP11_BATCH_COUNTS`", "src/main/java/ExperimentConfig.java",
     r"public static final int\[\] EXP11_BATCH_COUNTS = \{([^}]+)\}",
     "Batch counts of the warm-start study."),
    ("`WARM_START_FIRST_RATIO`", "src/main/java/ExperimentConfig.java",
     r"public static final double WARM_START_FIRST_RATIO = ([^;]+);",
     "Share of the database in the first batch under the `warm20` schedule; the rest is split equally."),
    ("`MemorySampler.INTERVAL_MS`", "src/main/java/MemorySampler.java",
     r"public static final long INTERVAL_MS = ([^;]+);",
     "Sampling period of the peak-memory series. A longer period can miss a peak."),
    ("`RunIsolation.GC_DEADLINE_MS`", "src/main/java/RunIsolation.java",
     r"private static final long GC_DEADLINE_MS = ([^;]+);",
     "Time allowed for the heap to settle between arms, so one arm's garbage is not charged to the next."),
    ("`RunIsolation.TEARDOWN_WAIT_SEC`", "src/main/java/RunIsolation.java",
     r"private static final long TEARDOWN_WAIT_SEC = ([^;]+);",
     "Time allowed for a timed-out arm to stop before the run is marked `OT`."),
    ("`HEAP`", "scripts/run.sh",
     r'HEAP="\$\{HEAP:-([^}]+)\}"',
     "JVM heap ceiling (`-Xmx`). Part of the identity of a measurement: numbers taken under different ceilings do not compare."),
    ("`ALGO_TIMEOUT_MIN`", "scripts/run.sh",
     r'ALGO_TIMEOUT_MIN="\$\{ALGO_TIMEOUT_MIN:-([^}]+)\}"',
     "Per-batch time limit in minutes passed as `--timeout`."),
    ("`HEAP` (Windows, cmd)", "scripts/run.bat",
     r'if "%HEAP%"=="" set HEAP=([^\s]+)',
     "Same ceiling as the POSIX launchers. It has to be the same number: a measurement taken under "
     "a different ceiling is not comparable, and B14 of `audit_results.py` refuses a tree that mixes them."),
    ("`HEAP` (Windows, PowerShell)", "scripts/run.ps1",
     r'if \(-not \$env:HEAP\) \{ \$env:HEAP = "([^"]+)" \}',
     "As above, for the PowerShell launcher."),
    ("garbage collector", "scripts/run.sh",
     # Not anchored on "exec java": the JVM is launched through a sleep inhibitor on macOS, so
     # the words before -Xmx are not fixed. Anchored on -Xmx"$HEAP" instead, which is.
     r"-Xmx\"\$HEAP\" (-XX:\S+)",
     "Collector selected on the command line; it changes both timing and the memory series."),
]


def extract():
    rows = []
    for label, rel, pattern, note in SPEC:
        path = ROOT / rel
        text = path.read_text(encoding="utf-8")
        m = re.search(pattern, text)
        if m is None:
            sys.exit("default_parameters: %s no longer matches in %s -- update SPEC" % (label, rel))
        line = text[: m.start()].count("\n") + 1
        value = " ".join(m.group(1).split()).strip()
        rows.append((label, "`%s`" % value, "`%s:%d`" % (rel, line), note))
    return rows


def table():
    rows = extract()
    w = ["| parameter | default | declared at | what it controls |",
         "|---|---|---|---|"]
    for label, value, where, note in rows:
        w.append("| %s | %s | %s | %s |" % (label, value, where, note))
    body = "\n".join(w)
    return (BEGIN + "\n\n" + body + "\n\n"
            + "Every per-experiment value -- participating datasets, minimum-utility thresholds,\n"
              "batch schedules, arm lists and per-experiment time limits -- is printed in full by\n"
              "`java -jar build/incremental-hausp-mining-1.0.0.jar --dump-config json`, which reads\n"
              "the same declarations the runs read.\n\n" + END)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--print", dest="show", action="store_true")
    a = ap.parse_args()

    generated = table()
    if a.show:
        print(generated)
        return 0

    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit("default_parameters: README.md has no %s ... %s block" % (BEGIN, END))
    start = text.index(BEGIN)
    stop = text.index(END) + len(END)
    current = text[start:stop]

    if a.check:
        if current == generated:
            print("default_parameters: README table matches the sources (%d parameters)" % len(SPEC))
            return 0
        print("default_parameters: README table is STALE. Run without --check to rewrite it.")
        import difflib
        for line in difflib.unified_diff(current.splitlines(), generated.splitlines(),
                                         "README.md", "sources", lineterm=""):
            print(line)
        return 1

    if current == generated:
        print("default_parameters: README already up to date (%d parameters)" % len(SPEC))
        return 0
    readme.write_text(text[:start] + generated + text[stop:], encoding="utf-8")
    print("default_parameters: rewrote the README table (%d parameters)" % len(SPEC))
    return 0


if __name__ == "__main__":
    sys.exit(main())
